# File: .github/workflows/kernel-build-arm64.yml

name: Kernel Build (ARM64)

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-kernel:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential bc bison flex libssl-dev libelf-dev \
            ccache python3 dwarves fakeroot kernel-package

      - name: Download ARM64 toolchain (aarch64)
        run: |
          mkdir -p ~/toolchains
          cd ~/toolchains
          wget https://releases.linaro.org/components/toolchain/binaries/latest-10/aarch64-linux-gnu/gcc-linaro-10.3.1-2021.07-x86_64_aarch64-linux-gnu.tar.xz
          tar -xf gcc-linaro-10.3.1-2021.07-x86_64_aarch64-linux-gnu.tar.xz
          echo "CROSS_COMPILE=$HOME/toolchains/gcc-linaro-10.3.1-2021.07-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-" >> $GITHUB_ENV

      - name: Compile ARM64 Kernel + Build .deb Package
        run: |
          export PATH=$(dirname $CROSS_COMPILE):$PATH
          make ARCH=arm64 defconfig
          make ARCH=arm64 CROSS_COMPILE=${CROSS_COMPILE} -j$(nproc)
          make ARCH=arm64 CROSS_COMPILE=${CROSS_COMPILE} -j$(nproc) deb-pkg

      - name: Upload kernel .deb packages
        uses: actions/upload-artifact@v3
        with:
          name: kernel-deb-packages
          path: ../*.deb
