name: Build Kernel msm8916 (ARM64) for Arch Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load environment variables from config.env
        run: |
          grep -v -E "^#|^\n" config.env | sed 's/ #.*//; s/#.*//' >> $GITHUB_ENV

      - name: Update Arch Linux and install dependencies
        run: |
          pacman -Syu --noconfirm --needed base-devel git sudo bc bison flex openssl libelf \
            xmlto kmod cpio perl xz git ccache dtc ncurses python fakeroot \
            aarch64-linux-gnu-gcc aarch64-linux-gnu-binutils aarch64-linux-gnu-glibc

      - name: Set toolchain path
        run: echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV

      - name: Clone Kernel Source
        run: |
          echo "HOME_DIR=$PWD" >> $GITHUB_ENV
          set -e
          git clone "$KERNEL_SOURCE" -b "$KERNEL_SOURCE_BRANCH" --depth=1 linux
          cd linux
          echo "KERNEL_DIR=$PWD" >> $GITHUB_ENV

      - name: Set Kernel ARCH
        run: |
          echo "ARCH=$KERNEL_ARCH" >> $GITHUB_ENV

      - name: Build kernel package with makepkg
        run: |
          cd $KERNEL_DIR
          cp $GITHUB_WORKSPACE/PKGBUILD .
          makepkg -s --noconfirm --skippgpcheck

      - name: Build kernel package with makepkg
        run: |
          cd $KERNEL_DIR
          makepkg -s --noconfirm --skippgpcheck

      - name: Upload kernel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: msm8916-kernel-artifacts
          path: |
            ${{ env.KERNEL_DIR }}/${{ env.KERNEL_IMAGE_NAME }}
            ${{ env.KERNEL_DIR }}/*.pkg.tar.zst
