name: Build Kernel msm8916 (ARM64) for Arch Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:base-devel

    steps:
      - name: Install build dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git sudo fakeroot bc bison flex openssl \
            elfutils ccache python ncurses dtc xmlto \
            gcc make cpio perl curl xz

      - name: Create builder user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder .
          chown -R builder:builder $PWD
        shell: bash

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Load environment variables
        run: |
          grep -v -E "^#|^\n" config.env | sed 's/ #.*//; s/#.*//' >> $GITHUB_ENV

      - name: Build kernel package with makepkg
        run: |
          sudo ls
          sudo -u builder bash -c "mkdir kernel && cd kernel && cp ../kernel-package/PKGBUILD . && makepkg -s --noconfirm"

      - name: Upload kernel package
        uses: actions/upload-artifact@v4
        with:
          name: linux-msm8916-pkg
          path: kernel-package/*.pkg.tar.zst
