name: Build Kernel msm8916 (ARM64) for Arch Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux/base:latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load environment variables from config.env
        run: |
          grep -v -E "^#|^\n" config.env | sed 's/ #.*//; s/#.*//' >> $GITHUB_ENV

      - name: Update Arch Linux and install dependencies
        run: |
          pacman -Syu --noconfirm --needed base-devel git sudo bc bison flex openssl libelf \
            xmlto kmod cpio perl xz git ccache dtc ncurses python fakeroot \
            aarch64-linux-gnu-gcc aarch64-linux-gnu-binutils aarch64-linux-gnu-glibc

      - name: Set toolchain path
        run: echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV

      - name: Clone Kernel Source
        run: |
          echo "HOME_DIR=$PWD" >> $GITHUB_ENV
          set -e
          git clone "$KERNEL_SOURCE" -b "$KERNEL_SOURCE_BRANCH" --depth=1 linux
          cd linux
          echo "KERNEL_DIR=$PWD" >> $GITHUB_ENV

      - name: Set Kernel ARCH
        run: |
          echo "ARCH=$KERNEL_ARCH" >> $GITHUB_ENV

      - name: Create PKGBUILD for ARM64 kernel
        run: |
          cd $KERNEL_DIR
          cat > PKGBUILD <<EOL
pkgbase=linux-msm8916
pkgver=\$(make kernelversion)
pkgrel=1
arch=('aarch64')
url="https://github.com/msm8916-mainline/linux"
license=('GPL2')
makedepends=('bc' 'bison' 'flex' 'openssl' 'libelf' 'xmlto' 'kmod' 'cpio' 'perl' 'xz' \
             'git' 'ccache' 'dtc' 'ncurses' 'python' 'fakeroot' \
             'aarch64-linux-gnu-gcc' 'aarch64-linux-gnu-binutils' 'aarch64-linux-gnu-glibc')
options=('!strip')
source=("linux-\${pkgver}.tar.xz")
sha256sums=('SKIP')

prepare() {
  cd linux-\${pkgver}
  
  # Apply patches if any
  for patch in ../*.patch; do
    [ -f "\$patch" ] && patch -p1 < "\$patch"
  done
}

build() {
  cd linux-\${pkgver}
  
  export ARCH=arm64
  export CROSS_COMPILE=aarch64-linux-gnu-
  
  make $KERNEL_DEFCONFIG
  make -j\$(nproc)
}

package() {
  cd linux-\${pkgver}
  
  export ARCH=arm64
  export CROSS_COMPILE=aarch64-linux-gnu-
  
  # Install modules
  make INSTALL_MOD_PATH="\${pkgdir}" modules_install
  
  # Install kernel image
  install -Dm644 arch/arm64/boot/Image "\${pkgdir}/boot/vmlinuz-msm8916"
  
  # Append DTB to kernel image
  cat arch/arm64/boot/Image arch/arm64/boot/dts/qcom/msm8916-wingtech-wt88047.dtb > "\${pkgdir}/boot/kernel-dtb"
  
  # Install headers (optional)
  make INSTALL_HDR_PATH="\${pkgdir}/usr" headers_install
}
EOL

      - name: Build kernel package with makepkg
        run: |
          cd $KERNEL_DIR
          makepkg -s --noconfirm --skippgpcheck

      - name: Upload kernel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: msm8916-kernel-artifacts
          path: |
            ${{ env.KERNEL_DIR }}/${{ env.KERNEL_IMAGE_NAME }}
            ${{ env.KERNEL_DIR }}/*.pkg.tar.zst
