# File: .github/workflows/kernel-build-arm64.yml

name: Kernel Build (ARM64)

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-22.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Environment
        run: |
          grep -v -E "^#|^\n" config.env | sed 's/ #.*//; s/#.*//' >> $GITHUB_ENV

      - name: Remove unused packages
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: false
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: Set swap to 10G
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Setup kernel build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential bc bison flex libssl-dev libelf-dev \
            ccache python3 dwarves fakeroot kernel-package git automake \
            lzop gperf zip curl zlib1g-dev g++-multilib libxml2-utils \
            bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools \
            pngcrush schedtool dpkg-dev liblz4-tool make optipng maven\
            libssl-dev pwgen libswitch-perl policycoreutils minicom \
            libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 \
            lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev \
            xsltproc unzip device-tree-compiler python2 python3 binutils-aarch64-linux-gnu

      - name: Download ARM64 toolchain (aarch64)
        run: |
          mkdir -p ~/toolchains
          cd ~/toolchains
          wget https://releases.linaro.org/components/toolchain/binaries/latest-10/aarch64-linux-gnu/gcc-linaro-10.3.1-2021.07-x86_64_aarch64-linux-gnu.tar.xz
          tar -xf gcc-linaro-10.3.1-2021.07-x86_64_aarch64-linux-gnu.tar.xz
          echo "CROSS_COMPILE=$HOME/toolchains/gcc-linaro-10.3.1-2021.07-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-" >> $GITHUB_ENV

      - name: Download kernel source
        run: |
          cd ~
          git clone --recursive ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} android-kernel --depth=1

      - name: Compile ARM64 Kernel + Build .deb Package
        run: |
          cd ~/android-kernel
          export PATH=$(dirname $CROSS_COMPILE):$PATH
          export ARCH=arm64
          make ARCH=arm64 defconfig
          make ARCH=arm64 CROSS_COMPILE=${CROSS_COMPILE} -j$(nproc)
          make ARCH=arm64 CROSS_COMPILE=${CROSS_COMPILE} -j$(nproc) deb-pkg

      - name: Upload kernel .deb packages
        uses: actions/upload-artifact@v3
        with:
          name: kernel-deb-packages
          path: ~/*.deb
