name: Build Kernel msm8916 (ARM64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (optional)
        uses: actions/checkout@v4

      - name: Load environment variables from config.env
        run: |
          grep -v -E "^#|^\n" config.env | sed 's/ #.*//; s/#.*//' >> $GITHUB_ENV

      - name: add arm64/armhf repo 
        run: |
          sudo cp /etc/apt/sources.list.d/ubuntu.sources /etc/apt/sources.list.d/ports.sources
          sudo sed -i.bak -e 's/^\(Suites:.*\)$/\1\nArchitectures: amd64 i386/' /etc/apt/sources.list.d/ubuntu.sources
          sudo sed -i.bak -e 's/^URIs:.*$/URIs: http:\/\/ports.ubuntu.com\/ubuntu-ports\//' /etc/apt/sources.list.d/ports.sources
          sudo sed -i -e 's/^\(Suites:.*\)$/\1\nArchitectures: armhf arm64/' /etc/apt/sources.list.d/ports.sources
          cat /etc/apt/sources.list.d/ports.sources

      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture armhf
          sudo dpkg --add-architecture arm64
          sudo apt-get update -qqy
          sudo apt-get upgrade -qqy
          sudo apt-get install -qqy \
            build-essential bc bison flex libssl-dev libelf-dev \
            ccache python3 fakeroot git libssl-dev:armhf libssl-dev:arm64\
            libncurses-dev device-tree-compiler xmlto \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            curl xz-utils debhelper-compat libssl-dev kmod cpio perl
  
      - name: Set toolchain path
        run: echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV

      - name: Clone Kernel Source
        run: |
          echo "HOME_DIR=$PWD" >> $GITHUB_ENV
          set -e
          git clone "$KERNEL_SOURCE" -b "$KERNEL_SOURCE_BRANCH" --depth=1 linux
          cd linux
          echo "KERNEL_DIR=$PWD" >> $GITHUB_ENV

      - name: Set Kernel ARCH
        run: |
          echo "ARCH=$KERNEL_ARCH" >> $GITHUB_ENV

      - name: Build Kernel and Package
        run: |
          set -e
          cd $KERNEL_DIR
          make "$KERNEL_DEFCONFIG"
          make -j$(nproc)

      - name: Build Package kernel
        run: |
          set -e
          cd $KERNEL_DIR
          make deb-pkg -j$(nproc)

      - name: Append DTB to Kernel Image
        run: |
          set -e
          cd $KERNEL_DIR
          cat arch/arm64/boot/Image.gz arch/arm64/boot/dts/qcom/msm8916-wingtech-wt88047.dtb > "$KERNEL_IMAGE_NAME"

      - name: Upload kernel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: msm8916-kernel-artifacts
          path: |
            ${{ env.KERNEL_DIR }}/${{ env.KERNEL_IMAGE_NAME }}
            ${{ env.HOME_DIR }}/*.deb
